version: '3.3'
services:
  vault-inmemory:
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token
      VAULT_LOCAL_CONFIG: {"backend": {"file": {"path": "/vault/file"}}}
    image: vault:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
    ports:
      - 8200:8200
    restart: unless-stopped
    volumes:
      - vault-testing-data:/vault/file

volumes:
  vault-testing-data:
